### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by SheepTester** [cse110-sp23-group20/fortune-teller#21]
Powell just said in lecture that our files should be clean 😬

we should do this towards the end of the project

**Comment by SheepTester** [comment]
I don't remember which files I was thinking of when I made this issue so I'm going to close this now. I think Powell might've been referring to stray comments (#60 and #61)

**Comment by bsalvania** [comment]
I feel like I remember him saying to take out the .vscode file, not sure, maybe someone else can verify
