### ISSUE TITLE
add custom cursor

### ISSUE THREAD

**Issue by ohuynh21** [cse110-sp23-group20/fortune-teller#38]
might be a cool thing to add

**Comment by SheepTester** [comment]
Hmmm, most websites usually don't change the cursor because it breaks user expectations, especially if the cursor isn't aligned the way they expect it. In addition, some users might have a custom cursor set up for accessibility reasons

Would be cool as a setting, though

**Comment by SheepTester** [comment]
We could add like particle effects flying off from the cursor as it moves around
