### ISSUE TITLE
JSDOCs generated documentation fails lint checks

### ISSUE THREAD

**Issue by bsalvania** [cse110-sp23-group20/fortune-teller#59]
Whenever JSDOCs generated the documentation, the coding format does not match prettier and so it fails. Want to find some way to fix this, like having the JSDOCs generated files have prettier run on it

**Comment by SheepTester** [comment]
Fixed in https://github.com/cse110-sp23-group20/fortune-teller/commit/ab2152b15be50e665fe1c9cdc53a4234e64b691b and https://github.com/cse110-sp23-group20/fortune-teller/commit/90f335933981cfed6349983209471eaf5972b1eb
