### ISSUE TITLE
Fortune cookie: cookie button disable

### ISSUE THREAD

**Issue by bsalvania** [cse110-sp23-group20/fortune-teller#69]
The cookie button (fortune cookie image) does not disable when the fortune button or the cookie button is clicked, so maybe that should be looked into.

**Comment by ohuynh21** [comment]
i think the issue is with this line:
const button = await page.$("button");

I changed it to this and it seems to work:
const button = await page.$("#fortune-button");

**Comment by bsalvania** [comment]
There's actually 2 buttons for opening the fortune cookie, one with an id of #fortune-button (the one that says "Open the cookie") and one with an id of #cookie-button (the fortune cookie image). While the fortune button will always disable when either is clicked, the cookie button never disables, which seems to be a bug.

**Comment by bsalvania** [comment]
That did fix the initial issues though so thanks for that
