### ISSUE TITLE
decide on global coding style snake, camel, etc

### ISSUE THREAD

**Issue by ohuynh21** [cse110-sp23-group20/fortune-teller#71]

**Comment by SheepTester** [comment]
For file names?

I think conventionally for JavaScript file names, people use `camelCase`, and for class names and IDs in HTML/CSS, people use `kebab-case`

**Comment by ohuynh21** [comment]
yeah that and for variables and folders. I think prettier already takes care of spacing and stuff for the HTML, CSS, and JS files but we should make sure that the variables and folders are all of the same case/style if they aren't already since there may be some inconsistencies in our sub-apps' style.

**Comment by ohuynh21** [comment]
addressed in #107
