### ISSUE TITLE
Fortune Cookie: Cleanup code

### ISSUE THREAD

**Issue by thinhgvo** [cse110-sp23-group20/fortune-teller#90]
- We just need to remove the code of the first version menu bar.

**Comment by thinhgvo** [comment]
- I removed these lines of code since I think it belongs to the old version of the horizontal menu bar.
![Remove1](https://github.com/cse110-sp23-group20/fortune-teller/assets/75603309/67722d69-512e-4ba9-a922-b17599a12e62)
![Remove2](https://github.com/cse110-sp23-group20/fortune-teller/assets/75603309/436ab6f2-01d1-4091-9e50-d65e5b1918a2)

**Comment by SheepTester** [comment]
this is true
